import os

import sys
import datetime
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker

from database_setup import Base, Cashier,Admin, Status,StatusType, FoodCategory,FoodCategoryHistory,FoodItem,Employee,EmployeeType,Transaction,CustomerOrder

engine = create_engine('sqlite:///ssds.db')
Base.metadata.bind = engine
DBSession = sessionmaker(bind=engine)
session = DBSession()

statustype1= StatusType(ststid='ST1',description='',entity='fooditem')
statustype2= StatusType(ststid='ST2',description='',entity='foodcategory')
statustype3= StatusType(ststid='ST3',description='',entity='employee')
statustype4= StatusType(ststid='ST4',description='',entity='transaction')
statustype5= StatusType(ststid='ST5',description='',entity='customerorder')


session.add(statustype1)
session.add(statustype2)
session.add(statustype3)
session.add(statustype4)
session.add(statustype5)

status1 = Status(stsid='S1',ststid='ST1',name='Available',description='')
status2 = Status(stsid='S2',ststid='ST2',name='Unavailable',description='')

status3 = Status(stsid='S3',ststid='ST2',name='Available',description='')
status4 = Status(stsid='S4',ststid='ST2',name='Unavailable',description='')

status5 = Status(stsid='S5',ststid='ST3',name='Working',description='')
status6 = Status(stsid='S6',ststid='ST3',name='Not-Working',description='')

status7 = Status(stsid='S7',ststid='ST4',name='Paid',description='')
status8 = Status(stsid='S8',ststid='ST4',name='Unpaid',description='')

status13 = Status(stsid='S9',ststid='ST5',name='Pending',description='')
status9 = Status(stsid='S10',ststid='ST5',name='Accepted',description='')
status10 = Status(stsid='S11',ststid='ST5',name='Rejected',description='')
status11= Status(stsid='S12',ststid='ST5',name='Delivery',description='')
status12 = Status(stsid='S13',ststid='ST5',name='Delivered',description='')

session.add(status1)
session.add(status2)
session.add(status3)
session.add(status4)
session.add(status5)
session.add(status6)
session.add(status7)
session.add(status8)
session.add(status9)
session.add(status10)
session.add(status11)
session.add(status12)
session.add(status13)

foodcat1=FoodCategory(cfid='FC1',name='DRINKS',description='FRESH JUICES, HOT & COLD BEVERAGES',stsid='S1')
foodcat2=FoodCategory(cfid='FC2',name='CHEESE',description='FOOD WITH CHEESE',stsid='S1')
foodcat3=FoodCategory(cfid='FC3',name='PIZZA',description='VEG/ NONVEG PIZZAS',stsid='S1')
foodcat4=FoodCategory(cfid='FC4',name='ZATTAR',description='ZATTAR',stsid='S1')
foodcat5=FoodCategory(cfid='FC5',name='SWEET',description='SWEETS/DESERTS',stsid='S1')
foodcat6=FoodCategory(cfid='FC6',name='LABNA',description='LABNA ITEMS',stsid='S1')
foodcat7=FoodCategory(cfid='FC7',name='SPINACH',description='SPINACH ITEMS',stsid='S1')
foodcat8=FoodCategory(cfid='FC8',name='MEAT',description='MEAT ITEMS',stsid='S1')
foodcat9=FoodCategory(cfid='FC9',name='FALAFEL',description='FALAFEL ITEMS',stsid='S1')#change.....................
foodcat10=FoodCategory(cfid='FC10',name='ALL',description='ALL ITEMS',stsid='S1')#change.....................



session.add(foodcat1)
session.add(foodcat2)
session.add(foodcat3)
session.add(foodcat4)
session.add(foodcat5)
session.add(foodcat6)
session.add(foodcat7)
session.add(foodcat8)
session.add(foodcat9)#change.....................
session.add(foodcat10)#change.....................


foodit1=FoodItem(fid='1',name='ORANGE',cfid='FC1',price=7,description='',stsid='S1')
foodit2=FoodItem(fid='2',name='MANGO',cfid='FC1',price=7,description='',stsid='S1')
foodit3=FoodItem(fid='3',name='LEMON',cfid='FC1',price=7,description='',stsid='S1')
foodit4=FoodItem(fid='4',name='COCTAIL',cfid='FC1',price=7,description='',stsid='S1')
foodit5=FoodItem(fid='5',name='STRAWBERRY',cfid='FC1',price=7,description='',stsid='S1')
foodit6=FoodItem(fid='6',name='BANANA MILK SHAKE',cfid='FC1',price=7,description='',stsid='S1')
foodit7=FoodItem(fid='7',name='MELON',cfid='FC1',price=7,description='',stsid='S1')
foodit8=FoodItem(fid='8',name='GUAVES',cfid='FC1',price=7,description='',stsid='S1')
foodit9=FoodItem(fid='9',name='KIWI',cfid='FC1',price=7,description='',stsid='S1')
foodit10=FoodItem(fid='10',name='TEA',cfid='FC1',price=2,description='',stsid='S1')
foodit11=FoodItem(fid='11',name='COFFEE',cfid='FC1',price=2,description='',stsid='S1')
foodit12=FoodItem(fid='12',name='BEVERAGE',cfid='FC1',price=2.5,description='',stsid='S1')
foodit13=FoodItem(fid='13',name='OREGENAL',cfid='FC1',price=1,description='',stsid='S1')
foodit14=FoodItem(fid='14',name='GALLON FRESH JUICE',cfid='FC1',price=20,description='',stsid='S1')
foodit15=FoodItem(fid='15',name='EGGS CHEESE',cfid='FC2',price=5,description='chhessses',stsid='S1')#change.....................
foodit16=FoodItem(fid='16',name='CHEESE HOT',cfid='FC2',price=5,description='chhessses',stsid='S1')#change.....................
foodit17=FoodItem(fid='17',name='CHEESE OLIVES',cfid='FC2',price=5,description='chhessses',stsid='S1')#change.....................
foodit18=FoodItem(fid='18',name='CHEESE ZATTAR',cfid='FC2',price=4,description='chhessses',stsid='S1')#change.....................
foodit19=FoodItem(fid='19',name='HONEY CHEESE',cfid='FC2',price=5,description='chhessses',stsid='S1')#change.....................
foodit20=FoodItem(fid='20',name='TOMATO CHEESE',cfid='FC2',price=5,description='chhessses',stsid='S1')#change.....................
foodit21=FoodItem(fid='21',name='CREAM CHEESE',cfid='FC2',price=4,description='chhessses',stsid='S1')#change.....................
foodit22=FoodItem(fid='22',name='CREAM CHEESE H',cfid='FC2',price=7,description='chhessses',stsid='S1')#change.....................
foodit23=FoodItem(fid='23',name='PIZZA VEG',cfid='FC3',price=8,description='',stsid='S1')#change.....................
foodit24=FoodItem(fid='24',name='PIZZA CHICKEN',cfid='FC3',price=8,description='',stsid='S1')#change.....................
foodit25=FoodItem(fid='25',name='PIZZA MEAT',cfid='FC3',price=7,description='',stsid='S1')#change.....................
foodit26=FoodItem(fid='26',name='PIZZA CHEESE',cfid='FC3',price=6,description='',stsid='S1')#change.....................
foodit27=FoodItem(fid='27',name='Bulbul\' nest',cfid='FC3',price=7,description='',stsid='S1')#change.....................
foodit28=FoodItem(fid='28',name='ZATTAR',cfid='FC4',price=2,description='',stsid='S1')#change.....................
foodit29=FoodItem(fid='29',name='ZATTAR OLIVES',cfid='FC4',price=3,description='',stsid='S1')#change.....................
foodit30=FoodItem(fid='30',name='ZATTAR TOMATOES',cfid='FC4',price=3,description='',stsid='S1')#change.....................
foodit31=FoodItem(fid='31',name='ZATTAR AL-SHALLAL',cfid='FC4',price=4,description='',stsid='S1')#change.....................
foodit32=FoodItem(fid='32',name='SWEET PASTRY',cfid='FC5',price=5,description='',stsid='S1')#change.....................
foodit33=FoodItem(fid='33',name='SWEET CHEESE',cfid='FC5',price=5,description='',stsid='S1')#change.....................
foodit34=FoodItem(fid='34',name='CREAM',cfid='FC5',price=4,description='',stsid='S1')#change.....................
foodit35=FoodItem(fid='35',name='CREAM HONEY',cfid='FC5',price=5,description='',stsid='S1')#change.....................
foodit36=FoodItem(fid='36',name='LABNA',cfid='FC6',price=4,description='',stsid='S1')#change.....................
foodit37=FoodItem(fid='37',name='LABNA ZATTAR',cfid='FC6',price=5,description='',stsid='S1')#change.....................
foodit38=FoodItem(fid='38',name='LABNA OLIVES',cfid='FC6',price=4,description='',stsid='S1')#change.....................
foodit39=FoodItem(fid='39',name='LABNA HOT',cfid='FC6',price=4,description='',stsid='S1')#change.....................
foodit40=FoodItem(fid='40',name='LABNA HONEY',cfid='FC6',price=5,description='',stsid='S1')#change.....................
foodit41=FoodItem(fid='41',name='LABNA CHEESE',cfid='FC6',price=5,description='',stsid='S1')#change.....................
foodit42=FoodItem(fid='42',name='LABNA SPINACH',cfid='FC6',price=5,description='',stsid='S1')#change.....................
foodit43=FoodItem(fid='43',name='LABNA FALAFEL',cfid='FC6',price=5,description='',stsid='S1')#change.....................
foodit44=FoodItem(fid='44',name='LABNA ZATTAR OLIVES',cfid='FC6',price=5,description='',stsid='S1')#change.....................
foodit45=FoodItem(fid='45',name='SPINACH SMALL',cfid='FC7',price=1,description='',stsid='S1')#change.....................
foodit46=FoodItem(fid='46',name='SPINACH BIG',cfid='FC7',price=3,description='',stsid='S1')#change.....................
foodit47=FoodItem(fid='47',name='SPINACH CHEESE',cfid='FC7',price=4,description='',stsid='S1')#change.....................
foodit48=FoodItem(fid='48',name='SPINACH EGGS',cfid='FC7',price=4,description='',stsid='S1')#change.....................
foodit49=FoodItem(fid='49',name='RAJLA VEGETABLE',cfid='FC7',price=3,description='',stsid='S1')#change.....................
foodit50=FoodItem(fid='50',name='BREAD MEAT',cfid='FC8',price=5,description='',stsid='S1')#change.....................
foodit51=FoodItem(fid='51',name='MEAT CHEESE',cfid='FC8',price=4,description='',stsid='S1')#change.....................
foodit52=FoodItem(fid='52',name='MEAT EGGS',cfid='FC8',price=5,description='',stsid='S1')#change.....................
foodit53=FoodItem(fid='53',name='MEAT SPINACH',cfid='FC8',price=5,description='',stsid='S1')#change.....................
foodit54=FoodItem(fid='54',name='FALAFEL SANDWICH',cfid='FC9',price=5,description='',stsid='S1')#change.....................
foodit55=FoodItem(fid='55',name='FALAFEL MIX',cfid='FC9',price=5,description='',stsid='S1')#change.....................
foodit56=FoodItem(fid='56',name='FALAFEL SMALL PLATE',cfid='FC9',price=5,description='',stsid='S1')#change.....................
foodit57=FoodItem(fid='57',name='FALAFEL BIG PLATE',cfid='FC9',price=5,description='',stsid='S1')#change.....................
foodit58=FoodItem(fid='58',name='FALAFEL PIECE(4)',cfid='FC9',price=5,description='',stsid='S1')#change.....................
foodit59=FoodItem(fid='59',name='POTATOES SMALL PLATE',cfid='FC9',price=5,description='',stsid='S1')#change.....................
foodit60=FoodItem(fid='60',name='POTATOES BIG PLATE',cfid='FC9',price=5,description='',stsid='S1')#change.....................

session.add(foodit1)
session.add(foodit2)
session.add(foodit3)
session.add(foodit4)
session.add(foodit5)
session.add(foodit6)
session.add(foodit7)
session.add(foodit8)
session.add(foodit9)
session.add(foodit10)
session.add(foodit11)
session.add(foodit12)
session.add(foodit13)
session.add(foodit14)
session.add(foodit15)#change.....................
session.add(foodit16)#change.....................
session.add(foodit17)#change.....................
session.add(foodit18)#change.....................
session.add(foodit19)#change.....................
session.add(foodit20)#change.....................
session.add(foodit21)#change.....................
session.add(foodit22)#change.....................
session.add(foodit23)#change.....................
session.add(foodit24)#change.....................
session.add(foodit25)#change.....................
session.add(foodit26)#change.....................
session.add(foodit27)#change.....................
session.add(foodit28)#change.....................
session.add(foodit29)#change.....................
session.add(foodit30)#change.....................
session.add(foodit31)#change.....................
session.add(foodit32)#change.....................
session.add(foodit33)#change.....................
session.add(foodit34)#change.....................
session.add(foodit35)#change.....................
session.add(foodit36)#change.....................
session.add(foodit37)#change.....................
session.add(foodit38)#change.....................
session.add(foodit39)#change.....................
session.add(foodit40)#change.....................
session.add(foodit41)#change.....................
session.add(foodit42)#change.....................
session.add(foodit43)#change.....................
session.add(foodit44)#change.....................
session.add(foodit45)#change.....................
session.add(foodit46)#change.....................
session.add(foodit47)#change.....................
session.add(foodit48)#change.....................
session.add(foodit49)#change.....................
session.add(foodit50)#change.....................
session.add(foodit51)#change.....................
session.add(foodit52)#change.....................
session.add(foodit53)#change.....................
session.add(foodit54)#change.....................
session.add(foodit55)#change.....................
session.add(foodit56)#change.....................
session.add(foodit57)#change.....................
session.add(foodit58)#change.....................
session.add(foodit59)#change.....................
session.add(foodit60)#change.....................



etype1=EmployeeType(etid='ET1',name='ADMIN',description='ADMIN')
etype2=EmployeeType(etid='ET2',name='CASHIER',description='CASHIER')

session.add(etype1)
session.add(etype2)

employee1=Employee(eid='E1',etid='ET2',fname='Sultan',lname='Lubbad',stsid='S1',salary=1000.5)
session.add(employee1)

user1= Admin(username="admin",password="admin")
user2= Cashier(username="cashier",password="cashier")
session.add(user1)
session.add(user2)
session.commit()
